
[package]
name = "ransomware_v2"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.2"
base64 = "0.22.1"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.8"
uuid = { version = "1.10", features = ["v4"] }
walkdir = "2"
